### ISSUE TITLE
Improvements to documentation

### ISSUE THREAD

**Issue by luisaFelixSalles** [ansys/pydpf-core#1711]
This issue tracks PyDPF-Core issues related to improvements made to the PyDPF-Core documentation

### Documentation system 
**_How should we organize the documentation website?_** 

**_Sections_**

 ### General #1762 

### User guide 
 
**First proposition**  (#1763 )

 After some reviews we got to make some changes :

- [x]    Change the tutorials approach (we were giving api reference we want a step by step guide)
- [x]    Make the solvers types more explicit 
- [x]    Make the tutorials titles more "action/feature centered"
  
 **Second proposition**  (#1779 )

 After some reviews we got to make some changes :

- [x] make a simple preview of the tutorials in the user guide page 
- [x] tutorials new layout 

**Third proposition** (#1876 ) (Final one)

 After some reviews we got to make some changes :
 
- [x]  Put tutorials section before the concepts
- [x]  In the basics one -> don't limit DPF to a post processing tool 
- [x]  Add a file with the links and references #1940 

### Examples

- [x] Add new subsections in the side bar #1752 
- [x] Reorganize where each example is -> kinda doing this with the tutorials rearrangement 

### API Reference 

- [ ] Reconfigure the side bar 
- [x] New designs for the cover page of this section #1755 

### Concepts

- [x] Merge with the user guide section (#1819 )

### Contribute

- [x]  move it to the the getting started page #1829 
- [x]  add tutorials guidelines #1950

**Comment by luisaFelixSalles** [comment]
### Layout changes

- Add caption in the toctree for better sidebar design 
-

**Comment by luisaFelixSalles** [comment]
IDEAS 

- Learning path -> discover PyDPF-Core, or discover our doc 
- Little quiz at the end of each tutorial
