### ISSUE TITLE
Missing facing when plotting a mesh

### ISSUE THREAD

**Issue by greschd** [ansys/pydpf-core#994]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

When plotting the attached `file.rst`, the top faces of the sandwich are missing. 

When the same data is loaded from distributed files, the same faces are typically present, but may randomly be missing.

Faces missing:

![image](https://github.com/ansys/pydpf-core/assets/5692808/9508faad-8d1c-4161-aad8-916ae6643f69)

Faces present:

![image](https://github.com/ansys/pydpf-core/assets/5692808/faa666e6-e0cb-4d0c-ad13-e7bc88d88332)

[rst_files.zip](https://github.com/ansys/pydpf-core/files/11746676/rst_files.zip)

### Steps To Reproduce

Run the attached Python script (reproduced below):

```python
import pathlib
from ansys.dpf import core as dpf

data_sources = dpf.DataSources()
data_sources_merged = dpf.DataSources()

# TODO: edit to the path where the `.rst` files are stored
data_path = pathlib.Path(__file__).parent.absolute() / "data2"

for i in range(3):
    filepath = data_path / f"distributed{i}.rst"
    data_sources.set_domain_result_file_path(str(filepath), i)
data_sources_merged.set_result_file_path(str(data_path / "file.rst"))

model = dpf.Model(data_sources)
model_merged = dpf.Model(data_sources_merged)

model.metadata.meshed_region.plot()
model_merged.metadata.meshed_region.plot()
```

[missing_faces.py.txt](https://github.com/ansys/pydpf-core/files/11746688/missing_faces.py.txt) 

### Which Operating System causes the issue?

Windows

### Which DPF/Ansys version are you using?

Ansys 2024 R1

### Which Python version causes the issue?

3.10

### Installed packages

Package                  Version
------------------------ --------
ansys-dpf-core           0.8.1
ansys-dpf-gate           0.3.1
ansys-dpf-gatebin        0.3.1
ansys-grpc-dpf           0.7.1
cachetools               5.3.1
certifi                  2023.5.7
charset-normalizer       3.1.0
colorama                 0.4.6
contourpy                1.1.0
cycler                   0.11.0
fonttools                4.40.0
google-api-core          2.11.0
google-api-python-client 2.89.0
google-auth              2.20.0
google-auth-httplib2     0.1.0
googleapis-common-protos 1.59.1
grpcio                   1.54.2
httplib2                 0.22.0
idna                     3.4
importlib-metadata       6.6.0
kiwisolver               1.4.4
matplotlib               3.7.1
numpy                    1.24.3
packaging                23.1
Pillow                   9.5.0
pip                      22.3.1
platformdirs             3.5.3
pooch                    1.7.0
protobuf                 4.23.2
psutil                   5.9.5
pyasn1                   0.5.0
pyasn1-modules           0.3.0
pyparsing                3.0.9
python-dateutil          2.8.2
pyvista                  0.39.1
requests                 2.31.0
rsa                      4.9
scooby                   0.7.2
setuptools               65.5.0
six                      1.16.0
tqdm                     4.65.0
uritemplate              4.1.1
urllib3                  1.26.16
vtk                      9.2.6
zipp                     3.15.0
